# Generated by Django 5.0.3 on 2024-04-02 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('issue', models.CharField(max_length=100)),
                ('issue_types', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('other', 'Other')], max_length=200)),
                ('issue_detail', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='help_desk')),
                ('status', models.CharField(blank=True, choices=[('in_progress', 'In-Progress'), ('solved', 'Solved'), ('not_solved', 'Not-Solved')], default='in_progress', max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
