# Generated by Django 5.0.3 on 2024-04-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_help_desk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
