# Generated by Django 5.0.3 on 2024-04-02 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopStore',
            fields=[
                ('laptop_name', models.CharField(max_length=100)),
                ('internal_serial_number', models.CharField(max_length=100)),
                ('external_serial_number', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('storage', models.IntegerField()),
                ('storage_types', models.CharField(blank=True, choices=[('ssd', 'SSD'), ('hdd', 'HDD')], max_length=200, null=True)),
                ('ram', models.CharField(max_length=100)),
                ('laptop_generation', models.CharField(max_length=100)),
                ('purchaser', models.CharField(max_length=100)),
                ('purchased_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('laptop_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'In Active')], max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('item_name', models.CharField(max_length=100)),
                ('item_categories', models.CharField(choices=[('hard_drive', 'Hard Drive'), ('wifi', 'Wi-Fi Equipment'), ('flash_disks', 'Flash Disks'), ('other', 'Other')], max_length=200)),
                ('item_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'In Active')], max_length=200)),
                ('item_detail', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('purchaser', models.CharField(max_length=100)),
                ('purchased_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopAllocation',
            fields=[
                ('allocation_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hst_IT_asset_management.laptopstore')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('allocation_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hst_IT_asset_management.store')),
            ],
        ),
    ]
