# Generated by Django 5.0.3 on 2024-04-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_first_name_alter_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('help_desk_admin', 'Help Desk Admin'), ('booking_admin', 'Booking Admin')], default='staff', max_length=20),
        ),
    ]
